### ISSUE TITLE
No Typescript type definitions available for bardjs

### ISSUE THREAD

**Issue by thaliaarchi** [wardbell/bardjs#10]
I have been using bardjs in my Typescript app and have been wanting a type definition file. When Typescript doesn't have a type definition file, it will complain that the bard functions don't exist. I created an issue on the [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) repository (the location of all Typescript definitions) to add this.

**Comment by WolfSoko** [comment]
Pushing it!

**Comment by wardbell** [comment]
Did you folks create a bardjs.d.ts? I haven't looked. I'm thinking of rewriting it in TS which would give me a d.ts "for free".

Of course if someone wants to do that before I get to it ... happiness!

**Comment by thaliaarchi** [comment]
I made the definitions for bardjs in definitely typed. They are currently being reviewed in this [pull request](https://github.com/borisyankov/DefinitelyTyped/pull/4760).

**Comment by TepigMC** [comment]
The tests they need are just basically usage tests to see if they match the definition file.
Here is their [documentation](http://definitelytyped.org/guides/contributing.html#tests) for what they want for the tests. They won't merge the pull request until these tests are added, so if anyone makes some, let me know.

**Comment by wardbell** [comment]
Sorry I haven't looked yet. I did this in version one of breeze.d.ts long ago but haven't had to since. Maybe this week unless someone beats me to it

**Comment by thaliaarchi** [comment]
I have made the definition files. Would you be willing to create a few use cases for each feature in bard? I need that so I can verify my definitions and also to create the test file.

For example:
`bard.appModule('app');`

**Comment by thaliaarchi** [comment]
I have finished the definition file and the tests for the definition file on DefinitelyTyped. It would be great if you could look at my definition file and tests to see if I typed everything correctly and also to see if my tests used all the functions correctly.

You can see the definitions at this [pull request](https://github.com/borisyankov/DefinitelyTyped/pull/4760).

**Comment by thaliaarchi** [comment]
The [pull request](https://github.com/borisyankov/DefinitelyTyped/pull/4760) has been merged into DefinitelyTyped.

**Comment by wardbell** [comment]
Thanks so very much for doing this ... especially writing those tests and steering it through the process. You are my hero today!

**Comment by thaliaarchi** [comment]
Thanks!

**Comment by tonyeung** [comment]
@TepigMC @wardbell sorry to necro this. How are we supposed to use bard.inject when using typescript?

When using bard.inject(), the tsc complains about every instance of the injected service being called, because we never created a variable to hold the service. 

`TS2304: Cannot find name 'authenticationManager`

As a workaround, declaring the variable in the first describe block AND assigning it the value of the service being generated by bard.inject() in the before each block will reduce the number of errors to 1

see below:

```
describe('authentication manager', () => {
    var expect = chai.expect;
    var AuthenticationManager: app.auth.IManageAuthentication; //<- typed service
    beforeEach(function () {
        bard.appModule('app.auth');
        bard.inject(this, 'authenticationManager');
        AuthenticationManager = authenticationManager; // <- only one error left here
    });
    it('should not be null',  () => {
        console.log('authentication manager should not be null');

        expect(AuthenticationManager).to.be.ok; // <- without the var at the top this would be a syntax error
    });
```

**Comment by JuHwon** [comment]
Sry to necrobump. @tonyeung i guess you already have solved this. 
Though for all others who might come here and search for answers: just checkout the [tests of the typings file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/bardjs/bardjs-tests.ts). Here you will find some answers how to use it ;)
