### ISSUE TITLE
NPM post install invokes bower, but bower is not on the package

### ISSUE THREAD

**Issue by voor** [wardbell/bardjs#11]
Hi, I'm utilizing badjs through webpack, so I install through npm.  After installing bardjs it tries to call "bower install" but I don't have bower installed, so it throws an error.

**Comment by ValentinH** [comment]
Yeap same error here. Then I also have the problem described here: https://github.com/slushjs/slush-angular/issues/14

**Comment by wardbell** [comment]
Suggestion?

**Comment by johnpapa** [comment]
install bower :)

**Comment by johnpapa** [comment]
we can remove the bower install script from package.json ... its not super important. thoughts ward?

**Comment by wardbell** [comment]
I'm ok with that. Whichever of us gets to it first 😃

**Comment by wardbell** [comment]
Done in 0.1.6
