### ISSUE TITLE
Update the Readme to point out bard also works for Jasmine

### ISSUE THREAD

**Issue by riddla** [wardbell/bardjs#13]
Hi Ward,

I stumbled upon your project some weeks ago and by only skimming the repo (or the description to be precise) I thought bard only offers help when testing with the mocha/chai combination. I returned today after watching parts of your (well made!)  [Pluralsight course on testing Angular](http://www.pluralsight.com/courses/play-by-play-angular-testing-papa-bell) in which bard is mentioned/used with Jasmine. 

Maybe you could update the description from `Mocha/chai spec helpers for testing angular v.1.x apps` to something along the lines of `Framework agnostic spec helpers for testing angular v.1.x apps.`  or `Spec helpers for testing angular v.1.x apps with mocha or jasmine or QUnit.`

PS: Thumbs up for this library, just by using the `inject` method I cleaned up my tests a lot.

**Comment by wardbell** [comment]
Glad it helps you. Why not create a pull request with language that you think would more clearly explain bard's range?

**Comment by wardbell** [comment]
FWIW,  it _should_ work with Jasmine but I haven't tested it. It _might_ work with QUnit or other test frameworks but I haven't tested them either. Thus I cannot be sure that it is as "agnostic" as you say ... and I'm not willing to commit to backing up such a claim.

**Comment by riddla** [comment]
Hi Ward.
Thanks for your response, I'll be glad to do a pull request.
FYI: I'm currently working on an Angular project tested with Jasmine `1.3` and found no problems. I did not use every feature, but at least the `appModule`, `inject` and `log` worked like a charm.

**Comment by johnpapa** [comment]
it **should** work with jasmine ... let us know if we missed anything

**Comment by riddla** [comment]
@wardbell: I might be mistaken or overlooking something, but I seem not be able to update the project description (using a pull request). The normal README is fine from my side, the description could be 
`Spec helpers for testing angular v.1.x apps with Mocha, Jasmine or QUnit` to match the Readme.

**Comment by riddla** [comment]
@johnpapa: I'll keep you posted, when I find the time and a proper usecase for the other bard features within my Jasmine specs. As stated above, `appModule`, `inject` and `log` worked smoothly.

**Comment by wardbell** [comment]
@riddla I believe those descriptions come from the _package.json_ and _bower.json_; I've updated accordingly

**Comment by riddla** [comment]
@wardbell, good catch about the _bower.json_ and the _package.json_. Updating them makes perfect sense, but the description I was originally referring to seems to be a Github only thing and can only be edited via the UI, http://stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github.

**Comment by wardbell** [comment]
Ah ... fixed it. Thanks

**Comment by riddla** [comment]
Just a quick follow-up: `bard.mockService` also works as expected within Jasmine specs, very helpful.
