### ISSUE TITLE
cannot test my routes using bardjs

### ISSUE THREAD

**Issue by caninojories** [wardbell/bardjs#14]
this is the error: Error: [$injector:unpr] Unknown provider: routerHelperProvider <- routerHelper

**Comment by caninojories** [comment]
im using the sample in the hottowel test of john papa
/\* jshint -W117, -W030 */
'use strict';
describe('main route', function () {
    describe('state', function () {
        var controller;
        var view = '/client/main/index.html';

```
    beforeEach(function() {
        module('app.main', bard.fakeToastr);
        bard.inject('$httpBackend', '$location', '$rootScope', '$state', '$templateCache');
    });

    beforeEach(function() {
        $templateCache.put(view, '');
    });

    it('should map state admin to url /admin ', function() {
        expect($state.href('main', {})).to.equal('/');
    });

    it('should map /admin route to admin View template', function () {
        expect($state.get('main').templateUrl).to.equal(view);
    });

    it('of admin should work with $state.go', function () {
        $state.go('main');
        $rootScope.$apply();
        expect($state.is('main'));
    });
});
```

});

**Comment by caninojories** [comment]
this is my route
(function() {
  'use strict';

  angular
    .module('app.main')
    .run(appRun);

```
appRun.$inject = ['routerHelper'];
/*ngInject*/
function appRun(routerHelper) {
  routerHelper.configureRoutes(getRoutes());
}

function getRoutes() {
  return [{
    state: 'main',
    config: {
      url: '/',
      templateUrl: '/client/main/index.html',
      controller: 'Main as vm',
      title: 'Main'
    }
  }];
}
```

}());

**Comment by wardbell** [comment]
Doesn't look like a bard problem. Are you sure the _routerHelper.js_ file is picked up by your test harness?  That is NOT the same thing as being sure it is picked up when the app runs.

**Comment by caninojories** [comment]
sorry.. i forgot to inject my dependency(app.core) in my admin module.. thanks for the answer..

**Comment by setuk** [comment]
what did you do to inject your dependency I am having the same issue - the dependency seems to be there in the module I am using though!
