### ISSUE TITLE
PhantomJS error, works well in Chrome and Firefox

### ISSUE THREAD

**Issue by lodnert** [wardbell/bardjs#2]
Hi!

I was just trying out bardjs and it seams to work fine in Chrome and Firefox, but when i run it in PhantomJS i get this error:

```
PhantomJS 1.9.8 (Mac OS X) Template Controller "before each" hook FAILED
    TypeError: 'undefined' is not a function (evaluating 'getCtxFromArgs.bind(this)')
        at bardInject (/Users/lodnert/projects/myapp/app/bower_components/bardjs/dist/bard.js:277)
        at /Users/lodnert/projects/myapp/test/spec/app/registry/template.controller.js:8
PhantomJS 1.9.8 (Mac OS X): Executed 1 of 1 (1 FAILED) ERROR (0.002 secs / 0 secs)
```

Here is the spec-file. 

```

describe('Controller: Auth', function () {
  var controller;
  beforeEach(function() {

      bard.appModule('myapp.auth');
      bard.inject('$controller', '$rootScope');

  });



  it('should be created successfully', function () {
    expect('hello').toBeDefined();
  });

});

```

Any ideas?

**Comment by rodleviton** [comment]
I am getting a similar error. I am also using phantomJS:

```
beforeEach(function() {
        bard.appModule('myModule');
        bard.inject(this, '$controller', '$log', '$q', '$rootScope');
    });
```

`TypeError: 'undefined' is not a function (evaluating 'getCtxFromArgs.bind(this)')
        at bardInject (/bower_components/bardjs/dist/bard.js:273)`

Any help would be really appreciated.

**Comment by rodleviton** [comment]
@lodnert I have just found the solution. Phantom JS does not support Function.prototype.bind so you will need a polyfill. @wardbell has made this available [here](https://github.com/wardbell/bardjs/blob/master/tests/helpers/bindPolyfill.js)

**Comment by lodnert** [comment]
Ah, awesome. I will try it out later today. Thanks!

**Comment by wardbell** [comment]
I think I should just fold this into bard so that no one encounters it again.

That's why I am reopening this issue.

**Comment by lodnert** [comment]
Sounds great, I was actually coming back here to suggest something like that.

**Comment by wardbell** [comment]
Done. See bardjs v.0.1.1
