### ISSUE TITLE
bardInject error

### ISSUE THREAD

**Issue by rodleviton** [wardbell/bardjs#3]
I am getting the following issue when using bard.inject().

```
beforeEach(function() {
        bard.appModule('myModule');
        bard.inject(this, '$controller', '$log', '$q', '$rootScope');
    });
```

`TypeError: 'undefined' is not a function (evaluating 'getCtxFromArgs.bind(this)')
        at bardInject (/bower_components/bardjs/dist/bard.js:273)`

Any help would be really appreciated.

**Comment by tgoyer** [comment]
I'm getting this same error.  At line 273, When I:

```
console.log(getCtxFromArgs.bind);
```

I get: 

```
 undefined
```

EDIT: Upon further analysis, it appears that Function.prototype.bind() is not implemented in PhantomJS.

2nd EDIT:  Upon further further analysis, the other issue already documents all this.  Disregard my rambling.  Haha

**Comment by wardbell** [comment]
See duplicate issue: https://github.com/wardbell/bardjs/issues/2#issuecomment-97065168
